name: Deploy to https://docs.sqlitecloud.io/
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to https://docs.sqlitecloud.io/
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.VERCEL_WEBHOOK_MAIN }}
        method: 'POST'