name: Documentation Search CI

on:
  push:
    branches:
      - main
      - stage

jobs:
  docsearch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: sqlitecloud/docsearch-action@v1
        with:
          project-string: ${{ secrets.PROJECT_STRING }}
          database: documentation.sqlite
          strip-astro-header: true
          strip-md-titles: true
          strip-jsx: true
          strip-html: true