name: Deploy to https://docs-stage.sqlitecloud.io/ 
on:
  workflow_dispatch:
  push:
    branches:
      - stage
    paths-ignore:
      - "README.md"

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to https://docs-stage.sqlitecloud.io/
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.VERCEL_WEBHOOK_DOCS_STAGE }}
        method: 'POST'